### ISSUE TITLE
Failed to run calibrate.py script

### ISSUE THREAD

**Issue by Akhil-Gurram** [Matchstic/depthmapper#2]
I am using jetson nano to compute stereo disparity maps using your script. But it fails to compute calibration. Please let me know how to fix this. 

Thanks in advance. 

Hit any key when you have the chessboard prepared
Calibration :: Computing...
Traceback (most recent call last):
  File "calibrate.py", line 20, in <module>
    main()
  File "calibrate.py", line 17, in main
    calibrator.compute_calibration(True)
  File "/home/madara/Documents/depthmapper/lib/calibration.py", line 68, in compute_calibration
    calibrator = StereoCalibrator( self.chessboard_rows,  self.chessboard_cols,  self.chessboard_size, (self.width, self.height))
  File "/home/madara/.local/lib/python3.6/site-packages/stereovision/calibration.py", line 190, in __init__
    corner_coordinates = np.zeros((np.prod(pattern_size), 3), np.float32)
  File "<__array_function__ internals>", line 6, in prod
  File "/home/madara/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3000, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/home/madara/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: cannot perform reduce with flexible type

**Comment by Matchstic** [comment]
I have no idea, sorry! It’s been a year or more since I last looked at this code. Might be your Python or numpy version?
